### ISSUE TITLE
Upgrade make the plugin misworking

### ISSUE THREAD

**Issue by sherpadawan** [pikim/grav-plugin-events#30] opened 2023-01-02 13:32 UTC
Since I updated to 1.1.7 Event tab in event page of type Event is not shown anymore ... I am unable to work with event metadata.
I did not try to reproduce it on  fresh install anyway, but seems to conflict with the latest grav version
Grav  v1.7.37.1 - Admin v1.10.37.1

**Comment by pikim** [comment] 2023-01-02 20:06
Thanks for the feedback. I never use the blueprints so I couldn't notice. Was caused by malformed yaml.
Also fixed in https://github.com/pikim/grav-plugin-events/commit/7f1a2046a71ee104cdac26e2749c2a7c962c1d10

**Closed by pikim** 2023-01-02 20:06 UTC
